#
# Copyright (C) 2026 The Android Open Source Project
# Copyright (C) 2026 SebaUbuntu's TWRP device tree generator
#
# SPDX-License-Identifier: Apache-2.0
#

DEVICE_PATH := device/realme/RE54C1L1

# For building with minimal manifest
ALLOW_MISSING_DEPENDENCIES := true

# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 := 
TARGET_CPU_VARIANT := generic
TARGET_CPU_VARIANT_RUNTIME := cortex-a53

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv7-a-neon
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := generic
TARGET_2ND_CPU_VARIANT_RUNTIME := cortex-a53

# APEX
DEXPREOPT_GENERATE_APEX_IMAGE := true

# Bootloader
TARGET_BOOTLOADER_BOARD_NAME := oppo8786_wlan
TARGET_NO_BOOTLOADER := true

# Display
TARGET_SCREEN_DENSITY := 240

# Kernel
BOARD_BOOTIMG_HEADER_VERSION := 2
BOARD_KERNEL_BASE := 0x40078000
BOARD_KERNEL_CMDLINE := bootopt=64S3,32N2,64N2 buildvariant=user
BOARD_KERNEL_PAGESIZE := 2048
BOARD_RAMDISK_OFFSET := 0x07c08000
BOARD_KERNEL_TAGS_OFFSET := 0x0bc08000
BOARD_MKBOOTIMG_ARGS += --header_version $(BOARD_BOOTIMG_HEADER_VERSION)
BOARD_MKBOOTIMG_ARGS += --ramdisk_offset $(BOARD_RAMDISK_OFFSET)
BOARD_MKBOOTIMG_ARGS += --tags_offset $(BOARD_KERNEL_TAGS_OFFSET)
BOARD_KERNEL_IMAGE_NAME := Image
BOARD_INCLUDE_DTB_IN_BOOTIMG := true
BOARD_KERNEL_SEPARATED_DTBO := true
TARGET_KERNEL_CONFIG := RE54C1L1_defconfig
TARGET_KERNEL_SOURCE := kernel/realme/RE54C1L1

# Kernel - prebuilt
TARGET_FORCE_PREBUILT_KERNEL := true
ifeq ($(TARGET_FORCE_PREBUILT_KERNEL),true)
TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/kernel
TARGET_PREBUILT_DTB := $(DEVICE_PATH)/prebuilt/dtb.img
BOARD_MKBOOTIMG_ARGS += --dtb $(TARGET_PREBUILT_DTB)
BOARD_INCLUDE_DTB_IN_BOOTIMG := 
BOARD_PREBUILT_DTBOIMAGE := $(DEVICE_PATH)/prebuilt/dtbo.img
BOARD_KERNEL_SEPARATED_DTBO := 
endif

# Partitions
BOARD_MAIN_SIZE := 5368709120
BOARD_SUPER_PARTITION_GROUPS := main
BOARD_MAIN_PARTITION_LIST := system product vendor
BOARD_SUPER_PARTITION_SIZE := 5368709120
BOARD_HAS_LARGE_FILESYSTEM := true
TARGET_USERIMAGES_USE_EXT4 := true
BOARD_SYSTEMIMAGE_PARTITION_TYPE := ext4
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := ext4
TARGET_COPY_OUT_VENDOR := vendor
BOARD_BOOTIMAGE_PARTITION_SIZE := 33554432
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 33554432
BOARD_FLASH_BLOCK_SIZE := 131072

# Platform
TARGET_BOARD_PLATFORM := mt6768

# Recovery
BOARD_INCLUDE_RECOVERY_DTBO := true
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true

# Security patch level
VENDOR_SECURITY_PATCH := 2021-08-01

# Verified Boot
BOARD_AVB_ENABLE := true
BOARD_AVB_MAKE_VBMETA_IMAGE_ARGS += --flags 3
BOARD_AVB_RECOVERY_KEY_PATH := external/avb/test/data/testkey_rsa4096.pem
BOARD_AVB_RECOVERY_ALGORITHM := SHA256_RSA4096
BOARD_AVB_RECOVERY_ROLLBACK_INDEX := 1
BOARD_AVB_RECOVERY_ROLLBACK_INDEX_LOCATION := 1

# Hack: prevent anti rollback
PLATFORM_SECURITY_PATCH := 2099-12-31
VENDOR_SECURITY_PATCH := 2099-12-31
PLATFORM_VERSION := 16.1.0

# ==============================================================================
# OrangeFox / TWRP Unified Framework Configuration
# ==============================================================================
# Basic UI & Language Layout Parameters
TW_THEME := portrait_hdpi
TW_EXTRA_LANGUAGES := false
TW_INPUT_BLACKLIST := "hbtp_vm"
TW_USE_TOOLBOX := true

# Include early MediaTek initialization scripts
TARGET_RECOVERY_DEVICE_MODULES := init.recovery.mt6768.rc

# 1. STANDALONE RECOVERY PARTITION CONFIGURATION (A-Only Single Slot Layout)
BOARD_SUPPORTS_RECOVERY_AS_BOOT := false
BOARD_USES_RECOVERY_AS_BOOT := false
BOARD_BUILD_SYSTEM_ROOT_IMAGE := false
AB_OTA_UPDATER := false

# 2. FIXED DISPLAY AND CORE BACKLIGHT POWER OVERRIDES
TW_SCREEN_BLANK_ON_BOOT := false
TW_NO_SCREEN_BLANK := true
BOARD_CHARGER_DISABLE_INIT_BLANK := true

# 3. KERNEL FRAMEBUFFER GRAPHICS (Matches Working Tree Specifications)
TARGET_RECOVERY_PIXEL_FORMAT := "BGRA_8888"
RECOVERY_GRAPHICS_USE_LINUX_FBDEV := true

# 4. HARDWARE PANEL BRIGHTNESS MAPPING PATHS (From your system log)
TW_BRIGHTNESS_PATH := "/sys/devices/platform/11004000.i2c7/i2c-7/7-0036/backlight/sgm_bl/brightness"
TW_MAX_BRIGHTNESS := 2047
TW_DEFAULT_BRIGHTNESS := 1200

# 5. DYNAMIC PARTITION INITIALIZATION LOOPS (Matched to Working Tree)
MAIN_PARTITION_LIST := system product vendor
BOARD_HAS_LARGE_FILESYSTEM := true
TW_INCLUDE_LPDUMP := false

# 6. ENCRYPTION & SYSTEM BINDER LINKERS (Fixed: Self-Contained Library Isolation)
TARGET_RECOVERY_LINK_SHARED_LIBS_FROM_RECOVERY_ALLOWED := true

# 7. ENCRYPTION AND DECRYPTION MAPPING ENGINE (Solves 0MB / Mount Fails)
TW_INCLUDE_CRYPTO := true
TW_INCLUDE_CRYPTO_FBE := true
TW_INCLUDE_FBE_METADATA_DECRYPT := true
RECOVERY_SDCARD_ON_DATA := true

# 8. ZIP INSTALLER AND FLASH TOOL ENGINE
TARGET_USES_MKE2FS := true
TW_INCLUDE_RESETPROP := true
TW_INCLUDE_REPACKTOOLS := false
TW_SKIP_COMPATIBILITY_CHECK := true
TARGET_OTA_ASSERT_DEVICE := RMP2102,RMP2103,RMP6768,RE54C1L1

# 9. USB AND MTP STACK ROUTING
TW_EXCLUDE_DEFAULT_USB_INIT := false

# 10. ORANGEFOX EXCLUSIVE FLAG COMPATIBILITY
OF_DEVICE_WITHOUT_KEYMASTER := 1
TW_EXCLUDE_TWRPAPP := true

# Force pure static execution and completely bypass the relink_binaries phase
TW_TARGET_USES_QCOM_BSP := false
TW_RECOVERY_ADDITIONAL_RELINK_BINARY_FILES :=
TW_RECOVERY_ADDITIONAL_RELINK_LIBRARY_FILES :=
TARGET_RECOVERY_LINK_SHARED_LIBS_FROM_RECOVERY_ALLOWED := true
FOX_DRASTIC_SIZE_REDUCTION := 1
