# ==============================================================================
# OrangeFox / TWRP Unified Framework Configuration
# ==============================================================================
# Basic UI & Language Layout Parameters
TW_THEME := portrait_hdpi
TW_EXTRA_LANGUAGES := true
TW_INPUT_BLACKLIST := "hbtp_vm"
TW_USE_TOOLBOX := true

# Include early MediaTek initialization scripts
TARGET_RECOVERY_DEVICE_MODULES := init.recovery.mt6768.rc

# Include low-level storage partition mapping modules
TARGET_RECOVERY_DEVICE_MODULES += libdm e2fsck mke2fs tune2fs

# 1. STANDALONE RECOVERY PARTITION CONFIGURATION (Not Recovery-As-Boot)
BOARD_SUPPORTS_RECOVERY_AS_BOOT := false
BOARD_USES_RECOVERY_AS_BOOT := false
BOARD_BUILD_SYSTEM_ROOT_IMAGE := false

# 2. FIXED DISPLAY AND CORE BACKLIGHT POWER OVERRIDES
TW_SCREEN_BLANK_ON_BOOT := false
TW_NO_SCREEN_BLANK := true
BOARD_CHARGER_DISABLE_INIT_BLANK := true

# 3. KERNEL FRAMEBUFFER GRAPHICS (Derived from your system log)
TARGET_RECOVERY_PIXEL_FORMAT := "RGBA_8888"
RECOVERY_GRAPHICS_USE_LINUX_FBDEV := true

# 4. HARDWARE PANEL BRIGHTNESS MAPPING PATHS
TW_BRIGHTNESS_PATH := "/sys/devices/platform/11004000.i2c7/i2c-7/7-0036/backlight/sgm_bl/brightness"
TW_MAX_BRIGHTNESS := 2047
TW_DEFAULT_BRIGHTNESS := 1200

# 5. DYNAMIC PARTITION INITIALIZATION LOOPS
MAIN_PARTITION_LIST := system vendor product
BOARD_HAS_LARGE_FILESYSTEM := true
TW_INCLUDE_LPDUMP := true

# 6. ENCRYPTION AND DECRYPTION MAPPING ENGINE (Solves 0MB / Mount Fails)
TW_INCLUDE_CRYPTO := true
TW_INCLUDE_CRYPTO_FBE := true
TW_INCLUDE_FBE_METADATA_DECRYPT := true
RECOVERY_SDCARD_ON_DATA := true

# 7. ZIP INSTALLER AND FLASH TOOL ENGINE
TARGET_USES_MKE2FS := true
TW_INCLUDE_RESETPROP := true
TW_INCLUDE_REPACKTOOLS := true
TW_SKIP_COMPATIBILITY_CHECK := true
TARGET_OTA_ASSERT_DEVICE := RMP2102,RMP2103,RMP6768,RE54C1L1

# 8. USB AND MTP STACK ROUTING
TW_EXCLUDE_DEFAULT_USB_INIT := false

# 9. ORANGEFOX EXCLUSIVE FLAG COMPATIBILITY
FOX_VERSION := "R12.0"
OF_MAINTAINER := "Custom"
OF_DEVICE_WITHOUT_KEYMASTER := 1
TW_EXCLUDE_TWRPAPP := true
